#!/bin/bash

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Ensure Nginx is running
sudo service nginx start

# Replace the default HTML content
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

# Restart Nginx without using systemctl
sudo service nginx restart

