#!/bin/bash
sudo apt update
sudo apt install -y nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
sudo sed -i "/server_name _;/a \ \ \ \ error_page 404 /404.html;\n\ \ \ \ location = /404.html {\n\ \ \ \ \ \ \ \ internal;\n\ \ \ \ }" /etc/nginx/sites-available/default
sudo service nginx restart
